{
    'name': 'Hotel Management',
    'version': '1.0',
    'category': 'Hotel',
    'summary': 'Comprehensive Hotel Management System',
    'author': 'Your Name',
    'website': 'https://yourwebsite.com',
    'depends': ['base', 'stock', 'sale_management','contacts'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/hotel_menu.xml',
        'views/hotel_room_views.xml',
        'views/hotel_reservation_views.xml',
        'views/housekeeping_views.xml',
        'views/restaurant_views.xml',
        'reports/occupancy_report.xml',
        'reports/revenue_report.xml',
        #'data/housekeeping_task_data.xml',
        #'data/room_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
